### ISSUE TITLE
How to get started integrating this into my project. 

### ISSUE THREAD

**Issue by xanderhd** [Flafla2/Vive-Teleporter#1]
Hi, 
Im having difficulty getting this to copy to my project. When i drag in the unzipped files, unity crashes. 
How do i add it to my project? I didnt see a asset package, and tried to add it to a blank project since i saw steamvr is included and couldnt get that to work either.

Thanks,
Alex

**Comment by Flafla2** [comment]
Perhaps you can try importing [SteamVR from the Asset Store](https://www.assetstore.unity3d.com/en/#!/content/32647) and importing all of my stuff (in the "Art", "Scripts", and "Shader" folders) separately.

I'll throw together a Unity package soon to make things a bit easier.

**Comment by Flafla2** [comment]
Hi, check the new [Getting Started](https://github.com/Flafla2/Vive-Teleporter#getting-started) section, as well as the .unitypackage in the [Releases Section](https://github.com/Flafla2/Vive-Teleporter/releases) and reopen this issue if you are having any more problems.
