### ISSUE TITLE
ViveNavMesh will still try to render a mesh with no material.

### ISSUE THREAD

**Issue by AlpyneDreams** [Flafla2/Vive-Teleporter#11]
ViveNavMesh will still try to draw its mesh even if GroundMaterial is null, which crashes the engine.

**Comment by Flafla2** [comment]
This is obviously an oversight, but I believe the engine crash is only present in Unity beta version 5.4b18 and earlier.  I reported the issue to Unity a few days ago (pertaining to the mesh being null, not the material, but materials were also effected.  See 5bd718c2000274cb15dac37abdcda19ca03863eb) and they fixed it in 5.4b19.  I'll add a quick null check to ViveNavMesh for earlier betas of course.

**Comment by Flafla2** [comment]
Fixed in version 2.0.0.
