### ISSUE TITLE
Room space preview is not appearing

### ISSUE THREAD

**Issue by markmanes** [Flafla2/Vive-Teleporter#16]
I am not clear what I am doing wrong -- but I have teleport working -- but the room area preview is not showing up.

**Comment by Flafla2** [comment]
Have you configured your Vive Nav Mesh correctly?  (make sure you click "Update Nav Mesh" on your ViveNavMesh component!)

**Comment by markmanes** [comment]
Well I see the mesh on the ground object - and I do go into the NavMesh prefab provided and click on update. Teleporting works fine--it sees the mesh but the area 'box' doesn't appear. I know it is something to do with the project because I load the sample  you provide and it does work there.

One item to disclose is that I just added the vive-teleporter folder to the Unity project I didn't think to look for the release tab so I didn't use the Unity package you created. Could that be the issue?

**Comment by DaveLMyers** [comment]
If you change the Border Material on the Border Renderer for the Teleport Vive that you attached to the Camera (eye) from "None" to "Room Area Border" you should see the room area preview. At least it worked for me.

**Comment by Flafla2** [comment]
@DaveLMyers This is correct.  The BorderRenderer is used to draw the roomscale area preview.  "Border Material" must be set for this to render correctly.
