### ISSUE TITLE
Vive Teleporter needs a way to tell the surrounding App that teleporting is in use

### ISSUE THREAD

**Issue by markmanes** [Flafla2/Vive-Teleporter#17]
There may be an understood standard for these types of things (which I do not know) but I find myself needing to modify the vive-teleport script so that I can tell the rest of my app to stop what it is doing in regards to controllers (i.e. disable the laser pointer I have attached to the controller). Is there a better way than modifying the vive-script which I would like to update as it moves forward to let the rest of the app know that the teleporter is use?

**Comment by mikeshultz** [comment]
You could change `private bool Teleporting = false;` to `public bool Teleporting = false;` within TeleportVive.cs and access it from your own scripts.  It still requires a modification, but it's pretty minor.

**Comment by Flafla2** [comment]
Fixed in 233f522
