### ISSUE TITLE
Tutorial Video for how to cheat and seemingly get the Vive-Teleporter to work on irregular surfaces

### ISSUE THREAD

**Issue by Xen0phobe** [Flafla2/Vive-Teleporter#20]
YouTube tutorial video:
[https://youtu.be/BMcOXQsUHlM](https://youtu.be/BMcOXQsUHlM)

How to get the Vive-Teleporter Unity asset to work, and how to cheat and seemingly get it to work on irregular surfaces.

This tutorial was made using the version of Vive-Teleporter from 6/20/2016. As Flafla2 continues to work on his Vive-Teleporter project the content in this video may become incorrect or obsolete. 

Unity version 5.4.b21
SteamVR plugin for Unity - v1.1.0

Recorded using XBox Game DVR

**Comment by Flafla2** [comment]
I'm closing this, as it isn't exactly a question / issue but a resource.  Thank you for your contribution / resource however!
