### ISSUE TITLE
Video: Multilevel Teleporting, Raycast Blocking, and ProBuilder Basic

### ISSUE THREAD

**Issue by Xen0phobe** [Flafla2/Vive-Teleporter#21]
Previous Video: [https://youtu.be/BMcOXQsUHlM](https://youtu.be/BMcOXQsUHlM)

In this video, I demonstrate multilevel teleportation using the Vive-Teleporter asset and how selective raycast blocking can be used to cheat a teleporter underneath irregular surfaces. I also discuss how ProBuilder Basic's "Set Collider" option makes creating invisible teleportation surfaces a slightly faster process.

Vive-Teleporter on Github:  [https://github.com/Flafla2/Vive-Teleporter](https://github.com/Flafla2/Vive-Teleporter/)

ProBuilder Basic: [https://www.assetstore.unity3d.com/en/#!/content/11919](https://www.assetstore.unity3d.com/en/#!/content/11919)

I'm using the version of Vive-Teleporter from 6/20/2016. As Flafla2 continues to update his Vive-Teleporter project the content of this video may become incorrect or obsolete. 

Unity version 5.4.b21
SteamVR plugin for Unity - v1.1.0

Recorded using XBox Game DVR

**Comment by Flafla2** [comment]
I'm closing this, as it isn't exactly a question / issue but a resource. Thank you for your contribution / resource however!
