### ISSUE TITLE
Changing Teleport Grid Size

### ISSUE THREAD

**Issue by Xen0phobe** [Flafla2/Vive-Teleporter#22]
I'm screwing-around with creating a virtual Dungeons & Dragons table where players can touch their token on the table and shrink down to its size. Simply increasing or decreasing the Scale Property of the SteamVR Camera Rig will make the player bigger or smaller in VR - so there's currently no problems in that department. The problem I'm having is changing the scale of the Vive-Teleporter grid. I figure I can adjust the Velocity and Acceleration of the Pointer to get a larger or smaller arc. I can adjust the size and spacing of the dotted-line and probably script the orange circle to increase and decrease in scale accordingly. But for the life of me, I can't seem to make the grid size budge from nine squares per meter. 

I looked through all the scripts for default size values and the closest thing I found was (I believe) in the NavMesh Editor script where the Vive-Teleporter NavMesh is serialized from the existing Unity Navmesh. In that script, there's a part of a function that calculates the NavMesh indices as 1/3 of some other value. I believe it's used to create the triangles for the Teleporter Navmesh. What I'm looking for is some variable that - if adjusted - will increase or decrease the size of the squares in the Teleportation Grid. If anyone can point me in the right direction I would be **very** grateful. Thank you. 😄 

PS - I apologize for the vagueness of my description. I'm laying in bed and I'm recalling what I saw in the code from memory. If anyone wants me to provide more detail, I would be more than happy to oblige once I'm vertical. 😋

**Comment by darksoul90** [comment]
I found the texture scale here:
assets>vive-teleporter>art>materials>ground
Maybe you can use it. :)

**Comment by Flafla2** [comment]
I'm going to close this as @darksoul90's answer is correct.  You want to change the ``Texture Scale`` Property of ``Assets>Vive-Teleporter>Art>Materials>Ground``.
