### ISSUE TITLE
Question: How do I add non horizontal objects to the NavMesh?

### ISSUE THREAD

**Issue by KReguieg** [Flafla2/Vive-Teleporter#27]
Hi, love your teleporter!

But how can I add: for example your "ramp" obstacle to the NavMesh so it is possible to teleport on it as well?

Best regards, Khaled.

**Comment by Flafla2** [comment]
This was deliberately not allowed because you can't actually walk up ramps in VR.  I would suggest revisiting your level design to make walkable areas flat.

Edit: If you are really desperate you can use the workaround detailed [here](https://github.com/Flafla2/Vive-Teleporter/issues/20)
