### ISSUE TITLE
Teleport button pauses the unity window instead of teleporting.

### ISSUE THREAD

**Issue by ManveerDhillon** [Flafla2/Vive-Teleporter#29]
Hi guys,  I used Taylor Shockeys youTube tutorial to thy this out [https://www.youtube.com/watch?v=uDwAIveGDU0].  Everything seems to work except when I Play to test. I see both controllers and the touch pad inticator when touching, but when I press the button to use the teleporter it just Pauses Unity and the HMD goes back to my Vive main scene.  I went through the tutorial twice to make sure I followed all the instructions.  Any ideas what the issue could be?

**Comment by Flafla2** [comment]
Is anything showing up in the Unity console?  I'm pretty sure Valve's SteamVR API automatically pauses the game whenever Debug.LogError is called.

**Comment by ManveerDhillon** [comment]
I missed a step in the navmesh configuration... Sorry. All works fine!
