### ISSUE TITLE
Teleport Location Should Change Colour When Valid / Invalid

### ISSUE THREAD

**Issue by hamaluik** [Flafla2/Vive-Teleporter#3]
Right now, the location you're about to teleport to is always lit up as orange—even if you can't teleport there.

It would be very handy to have this marker turn green when the teleport location is within the navmesh bounds, and have it red (or orange or whatever) when it is outside of the bounds, but still hitting the ground.

PS: thanks for this awesome library, I'll definitely be using it!

**Comment by Flafla2** [comment]
Addressed with 011b60c.  I have added an "invalid selection pad" prefab slot in the Parabolic Pointer, so now you can customize the behavior of the pointer as desired.
