### ISSUE TITLE
Ignore Triggers when doing the Raycast

### ISSUE THREAD

**Issue by derekhendrickx** [Flafla2/Vive-Teleporter#33]
When there are big Trigger area in the scene (see the screenshot below), you can't teleport inside them. When doing the Raycast, the Triggers aren't ignored.

![capture](https://cloud.githubusercontent.com/assets/1218149/19362565/28011106-9155-11e6-9e8a-2d9a35ad3ebb.PNG)

**Comment by derekhendrickx** [comment]
See [PR34](https://github.com/Flafla2/Vive-Teleporter/pull/34)

**Comment by Flafla2** [comment]
Fixed in #34
