### ISSUE TITLE
New interesting version of Teleporting for HTC Vive (Closed source)

### ISSUE THREAD

**Issue by Vytek** [Flafla2/Vive-Teleporter#35]
https://www.assetstore.unity3d.com/en/#!/content/61561

Is it possible to modify you code:

1) Color red when arc hit not autorized zone?
2) Rotate the play area with Steam Controller?

Thank you for your superb plugin ;-)

**Comment by luhillxs** [comment]
Hey, I have a simple solution for the 1st question:

In ParabolicPointer.cs, do this:
1. Add "public Material GraphicMaterialForbidden;" in line 23, right after public Material GraphicMaterial (actually u can add it anywhere u like);
2. Replace "Graphics.DrawMesh(ParabolaMesh, Matrix4x4.identity, GraphicMaterial, gameObject.layer);" (probably in around line 217) to the following code:
        if (ShouldDrawMarker)
            Graphics.DrawMesh(ParabolaMesh, Matrix4x4.identity, GraphicMaterial, gameObject.layer);
        else
            Graphics.DrawMesh(ParabolaMesh, Matrix4x4.identity, GraphicMaterialForbidden, gameObject.layer);
3. Save the script, return to your scene and click somewhere, wait for reloading the script. Then you will find an additional slot called "Graphic Material Forbidden" appear in the Inspector (right after Graphic Material slot if you place it in the line I mentioned) 
4. Find the material "Parabolic Selector", duplicated it and rename, then modify the color you want the arc to be when it hit not authorized zone;
5. Drag the duplicated "Parabolic Selector" material into "Graphic Material Forbidden" slot.

Hope it will help :)

**Comment by Flafla2** [comment]
In the near-term, I am going to work on some solutions to customizing the aesthetics of the teleporter - I'm going to close this issue though as the linked asset is off-topic.

To anyone reading this, note that the linked asset does not indicate teleportable surfaces visually, so I would argue that my open-source solution is superior :)
