### ISSUE TITLE
Changing teleportation distance

### ISSUE THREAD

**Issue by wattsandy** [Flafla2/Vive-Teleporter#36]
Awesome tool, really really useful!

I have a question - what is used to control the distance you can teleport? Currently the model I have has got a relatively small teleporting distance which, when used in a large model environment, means quite a few individual teleports to move across a large space.

Any help would be greatly appreciated!

**Comment by KellanHiggins** [comment]
I think you have to increase the velocity of the arc.

**Comment by jBachalo** [comment]
Doesn't work.
Anyone have a solution?
Should be an adjustable parameter

**Comment by Asmodeus317** [comment]
You can change distance with the acceleration component, you just need to increase the 'point count' too otherwise the parabola can't reach.

**Comment by Flafla2** [comment]
Hi, I'm going to close this issue as I have added more information in the Parabolic Pointer documentation that addresses this.  Feel free to reopen if you have any further questions.
