### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by jBachalo** [Flafla2/Vive-Teleporter#38]
Unless I am missing something I think the documentation could be clarified in Step 1
**_Next you need to bake a Navigation mesh ("Navmesh") in Unity. This can be done in the Navigation window (Window > Navigation)._**

Not mentioned is that you need to select a piece of static geometry that represents your ground and THEN go to Navigation, Bake.
At least that is what works for me

**Comment by Flafla2** [comment]
This is not true.  For more information on how Navmesh baking works in unity, see [this page in the unity manual](https://docs.unity3d.com/Manual/nav-BuildingNavMesh.html).

Perhaps you didn't set all of your objects as "navigation static".
