### ISSUE TITLE
Crash on adding NavMesh

### ISSUE THREAD

**Issue by alexalder** [Flafla2/Vive-Teleporter#6]
Hi,
I'm trying to setup your prefab, when i add the NavMesh into the heirarchy Unity crashes, every single time, no matter where i put it.
Could it be because i'm on the 5.4 beta?
Thanks

**Comment by Flafla2** [comment]
Hmm, users have been expressing issues with the 5.4 beta.  I will install it and take a look.

**Comment by Flafla2** [comment]
Update: I have found the cause of the crash and a hotfix should come within the next 24 hours.

**Comment by Flafla2** [comment]
Fixed with above commit.
