### ISSUE TITLE
"Update Navmesh Data" button not visible until after code modification

### ISSUE THREAD

**Issue by johngillett** [Flafla2/Vive-Teleporter#7]
I wasn't able to see the "Update Navmesh Data" button or anything after it in the Navmesh object. I kept getting a null reference error (or some similar reference error). The error was from this line: 
bool HasMesh = mesh.SelectableMesh.vertexCount != 0 || mesh.SelectableMeshBorder.Length != 0;

The error was being reported on the SelectableMesh object. 

I moved this line right after the following GUI Button If statement and everything worked from then on. 

I've since moved the line back to its original position and it continues to work.

**Comment by Flafla2** [comment]
This bug has been fixed in the latest release (version 1.0.2).
